### ISSUE TITLE
I am getting 'Unimplemented nodes' exception

### ISSUE THREAD

**Issue by kiyanisarah** [AlexanderLutsenko/nobuco#20]
I am trying to convert my Detr model but i am getting this error:
Traceback (most recent call last):
  File "===/DETR/nobuco_script.py", line 32, in <module>
    keras_model = nobuco.pytorch_to_keras(
  File "==/DETR/env/lib/python3.10/site-packages/nobuco/convert.py", line 331, in pytorch_to_keras
    raise Exception('Unimplemented nodes')
Exception: Unimplemented nodes

using these checkpoints to convert:
CHECKPOINT = "TahaDouaji/detr-doc-table-detection"

**Comment by AlexanderLutsenko** [comment]
Hi! Could you provide a minimal reproducible example? Another thing is to set `save_trace_html=True` and send me `trace.html`.

**Comment by kiyanisarah** [comment]
> Hi! Could you provide a minimal reproducible example? Another thing is to set `save_trace_html=True` and send me `trace.html`.

Here are the contents of the html file as txt: 
[trace.txt](https://github.com/AlexanderLutsenko/nobuco/files/13888950/trace.txt)

**Comment by AlexanderLutsenko** [comment]
Ah, I see. There was a bunch of problems in specific node converters (namely, `sin`/`cos`, `truncated div`, `cumsum`). Fixed those in `v0.11.2`. I don't know where your DETR comes from, so I tested on a popular implementation from `transformers` lib, which looks pretty similar. Try [this example code](https://github.com/AlexanderLutsenko/nobuco/blob/a91314c458265d27e60116a31f789f2334c0faa0/examples/detr.py), does it work for you?

I also noticed all of your `Conv2d` and `MaxPool2d` layers are broken. This is a separate issue, probably due to incompatible version of `cudnn`/`cudatoolkit` (see [here](https://forum.image.sc/t/dnn-library-is-not-found-problem-with-tensorflow/81673)). To confirm this, try disabling your GPU:

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = ""
```

**Comment by AlexanderLutsenko** [comment]
> ValueError: Layer conv2d weight shape (7, 7, 800, 64) is not compatible with provided weight shape (7, 7, 3, 64).

That could be because the second input to the `DetrForObjectDetection` model (`pixel_mask`) should be of same size as the image.
